const DISPLAY_ALERT = "SHOW_ALERT";
const CLEAR_ALERT = "CLEAR_ALERT";

const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
const LOGOUT_USER = "LOGOUT_USER";

const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
const HANDLE_JOB_CHANGE = "HANDLE_JOB_CHANGE";
const CLEAR_JOB_VALUES = "CLEAR_JOB_VALUES";

const CREATE_JOB_BEGIN = "CREATE_JOB_BEGIN";
const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
const CREATE_JOB_ERROR = "CREATE_JOB_ERROR";

export {
    DISPLAY_ALERT,
    CLEAR_ALERT,
    REGISTER_USER_BEGIN,
    REGISTER_USER_SUCCESS,
    REGISTER_USER_ERROR,
    LOGIN_USER_BEGIN,
    LOGIN_USER_SUCCESS,
    LOGIN_USER_ERROR,
    TOGGLE_SIDEBAR,
    LOGOUT_USER,
    UPDATE_USER_BEGIN,
    UPDATE_USER_SUCCESS,
    UPDATE_USER_ERROR,
    HANDLE_JOB_CHANGE,
    CLEAR_JOB_VALUES,
    CREATE_JOB_BEGIN,
    CREATE_JOB_SUCCESS,
    CREATE_JOB_ERROR,
};
